Repository pablues/agile-project, pull requests merged in 2025-04, with the labels that each got.

#19 updated views
  views/views.py
Labels: enhancement

#24 views fix
  views/views.py
Labels: bug

#28 syntax error fixed
  tests/tests.py
Labels: bug

#34 added sprint models + user story
  views/views.py
Labels: enhancement

#39 token error fixed
  templates/project.html
Labels: bug

#42 views fix
  views/views.py
Labels: wontfix

#43 base html update
  templates/base.html
Labels: wontfix

#44 urls fix
  urls/urls.py
Labels: wontfix

#49 New Features Added in Model
  models/model1.py
Labels: enhancement

#57 Users with tasks
  views/views.py
Labels: enhancement
